trainingInput:
          #scaleTier: BASIC
          #  scaleTier: BASIC_GPU
          #    #scaleTier: STANDARD_1
          #      #scaleTier: PREMIUM_1
          #
          scaleTier: CUSTOM
          masterType: standard
          parameterServerType: standard
          workerType: complex_model_m
          parameterServerCount: 1
          workerCount:2
